### PR TITLE
Add flipsign, eps, signbit

### PR DESCRIPTION
**Pull request by tkoolen**

### CODE REVIEW

**Comment by jverzani** [comment]
Great. Thanks. Once the checks complete, I'll merge in. I'm working on a branch to match changes to v0.6. I'll add an `iszero` method to this then.

**Comment by tkelman** [comment]
just curious, what ends up needing to use `eps` of a symbolic object?

**Comment by tkoolen** [comment]
As I'm sure you know, in code written with floating point types in mind, there are sometimes special cases that need to be handled differently because of either limited floating point precision, or because e.g. the limit of a function as the argument goes to some value exists, but in floating point math the result would work out to be `0. / 0.`. This happens e.g. [around singularities in minimal representations of 3D orientation](https://github.com/tkoolen/RigidBodyDynamics.jl/blob/30ba38f785256c50af279f49dc22c715bc6b60fa/src/spatial.jl#L442).

It's nice to have that same code work for symbolic types, where there are no issues due to limited precision. Defining `eps` for `Sym` to be `Sym(0)` makes it so that such `eps`-based special cases are simply skipped.

**Comment by jverzani** [comment]
Well said. In SymEngine we had a test that quadgk worked with symbolic types as they are callable. This just extends that usage.

**Pull request merged**
