### PR TITLE
lambdify for matrices, close #218

### LINKED ISSUE #218: lambdify apply to matrix (or array) or number
In python+sympy environment, we can easily lambdify a matrix expression into a function or lambdify the expression to return a sympy expression:

    from sympy import *
    s = Matrix([[1, 0], [0, 1]])
    x, y = symbols('x y')
    
    fun = lambdify(x, x * s)
    print(fun(2))
    
    fun1 = lambdify(x,x + y)
    print(fun1(2))

In the above code, `fun` returns a numpy array, and `fun1` returns a sympy expression. 

However, I cannot use `lambdify` like these in `SymPy.jl`. Especially, in julia `lambdify(1,x)` or more specificaly `lambdify(PI,x)` are 
 illegal.  Any recommendations?

### PR DESCRIPTION
**Pull request by jverzani**

### CODE REVIEW

**Comment by mistguy** [comment]
I propose to add a method including a `convert` function here.
```julia
function lambdify(::Type{Tout}, exs::Array{T, N}, vars = union(free_symbols.(exs)...); kwargs...) where {T <: Sym, N} where Tout
    f = lambdify.(exs, (vars,)) # prevent broadcast in vars
    (args...) -> convert.(Tout, map.(f, args...))
end
```

Otherwise, the returned array may not have a specific type. It's up to the user to decide what type to convert to.

**Comment by jverzani** [comment]
Thanks for the idea! I used a slightly different version where the `eltype` is specified for conversion.

**Comment by mistguy** [comment]
Thank you. Type as a keyword argument is fine. However, it seems it's a custom for julia functions to take the type as the first argument. So maybe it's better to do
```
function lambdify(::Type{T}, exs::Array{S, N}, vars = union(free_symbols.(exs)...); kwargs...) where {S<:Sym, N} where T
    f = lambdify.(exs, (vars,)) # prevent broadcast in vars
    if T == Void
        (args...) -> map.(f, args...)
    else
        (args...) -> convert(Array{T,N}, map.(f, args...))
    end
end

function lambdify(exs::Array{S, N}, vars = union(free_symbols.(exs)...); kwargs...) where {S<:Sym, N} 
    return lambdify(Void, exs, vars, kwargs...)
end
```

**Comment by jverzani** [comment]
Thanks again for the feedback. I'm not super keen on this suggestion though. That pattern is used a lot, but most often for dispatch. This is not about dispatch but rather adjusting the output, which is typically related to keyword arguments. I think I'll leave as is unless there is a more compelling reason. At some point, I should see how much effort it takes to more closely mirror the calling pattern from the SymPy python function, as that might lead to the least surprise for users coming over from that usage. Not sure that is a high priority, as this interface seems most natural to me for a Julia user.

**Pull request merged**
