### PR TITLE
Mzaffalon pull request/09a0d51f

### PR DESCRIPTION
**Pull request by jverzani**

### CODE REVIEW

**Comment by jverzani** [comment]
Sorry @mzaffalon I didn't do this right. I thought I could push to your PR, but didn't seem to have the proper permissions. Will merge this if checks complete. Thanks!

**Comment by jverzani** [comment]
@mzaffalon We may have to hold off on adding the "testset" feature. I can work around the v0.4 issues, but fear there are issues with v0.6 that come up. I think merging #20167 will fix this, but don't know for sure.

**Comment by mzaffalon** [comment]
No problem, the PR is ready and can wait.
`BaseTestNext` is only required for 0.4: should there be a conditional in `REQUIRE` to prevent from making it a requirement for Julia >= 0.5?

**Comment by mzaffalon** [comment]
I guess this one can be closed too.

**Pull request closed without merging**
