### PR TITLE
Docfix; close  issue  #357

### LINKED ISSUE #357: linsolve fails
When I was trying the tutorials in examples/solvers.md, I find these are probably broken. 
solve seems to be good:
```julia
julia> @vars x y z
julia> solve([x + y + z - 1, x + y + 2*z - 3 ], (x, y, z))
Dict{Any,Any} with 2 entries:
  z => 2
  x => -y - 1
```
linsolve produces an empty set (this is also shown in the notebook version of tutorial):
```julia
julia> linsolve([x + y + z - 1, x + y + 2*z - 3 ], (x, y, z))
∅
```
solveset can't even run:
```julia
solveset([x + y + z - 1, x + y + 2*z - 3 ], (x, y, z))
ERROR: MethodError: no method matching solveset(::Array{Sym,1}, ::Tuple{Sym,Sym,Sym})
Closest candidates are:
  solveset(::SymPy.SymbolicObject, ::Any...; kwargs...) at C:\Users\melonedo\.julia\packages\SymPy\QNFlL\src\importexport.jl:96
Stacktrace:
 [1] top-level scope at REPL[17]:1
```
Are there any caveats in using this module?

### PR DESCRIPTION
**Pull request by jverzani**
Close #357 by using  Documenter and  `jldoctest`  for the tutorial and  introduction documents.

- [x] Need to   remove  Examples directory 

- [x] Need assistance setting up keys for JuliaPy

### CODE REVIEW

**Comment by jverzani** [comment]
Hi @ararslan . You were very helpful setting up a deployment  key for  Polynomials.jl,  do  you think  you could help again? In following the instructions produced by `DocumenterTools.genkeys`  I  got stuck adding a public key. I  also can't add  to  `https://travis-ci.com/JuliaPy/SymPy.jl/settings`,  but  I  think `https://travis-ci.com/jverzani/SymPy.jl/settings` will work for that. Sorry to  take your time, but I'm admittedly  new  to using  Documenter, and  think   I  need some assistance  with this part.

**Comment by ararslan** [comment]
I'd be happy to help but in this case I can't, since, like you, I don't have owner-level privileges in the organization. That's required to access repository settings and add the necessary deployment keys. @stevengj, could you perhaps take care of this?

**Comment by jverzani** [comment]
Thanks for the response!

**Comment by stevengj** [comment]
I've changed @jverzani and @ararslan to have Owner access.

**Comment by jverzani** [comment]
Thanks!

**Comment by ararslan** [comment]
@jverzani, looks like you added a deploy key for Documenter. Are you all set here then or is there anything else I can help with?

**Comment by jverzani** [comment]
@ararslan Thanks for following up. I  thing I'm good to go. Your help was very much appreciated.

**Pull request merged**
