### PR TITLE
Fix CSE for scalar and array cases

### PR DESCRIPTION
**Pull request by cdsousa**
Right now, at least in my setup, the output part of CSE results is nested inside an unnecessary array.
Additionally, the CSE of matrices simply fails.
This PR tries to fix that.

I'm not convinced that this is not a problem of my setup alone.
That can be confirmed by trying the added tests yourselves.

### CODE REVIEW

**Comment by jverzani** [comment]
Thanks for this.

This is failing on older versions due to `where T<:SymbolicObject` syntax. I think I need to make a 0.6+ branch to place these changes and then drop support for older versions.

**Comment by cdsousa** [comment]
Oh, yeah, I overlooked that.
I can redo the commit with the older syntax. ?

**Comment by jverzani** [comment]
That would be best. We can change all at once later. Thx

**Comment by cdsousa** [comment]
Done. And rebased.

**Comment by jverzani** [comment]
Thanks again!

**Pull request merged**
