### PR TITLE
Fix several issues in new @syms

### PR DESCRIPTION
**Pull request by matthieubulte**
Fix @syms: 'tuple' syntax doesn't create GlobalRefs anymore; creating a single sym doesn't crash anymore.

See #418.

@jverzani: to answer your other question, no need to change the current master I think. Maybe it would be wise if we leave this PR open while you still work on the docs and merge it right before the docs is ready and we feel confident enough to release it.

### CODE REVIEW

**Comment by matthieubulte** [comment]
Add support for tensor declaration of the form
```julia
@syms x[1:5, 3:9]
```

**Comment by jverzani** [comment]
This is really nice. I had to move where `decl.jl` got included and added one more entry to the dictionary to support negative indices. One thing changed that would be nice, if possible, to get back. The  return value is generic. It was:

```
julia> @syms a b
(a,b)
```

But is now

```
julia> @syms a b
(SymPy.sym, SymPy.sym)
```

I thought I could fix, but am not really up on macros the way I should be. Is it a simple adjustment?

**Comment by matthieubulte** [comment]
My bad, this is a mistake in the code I shipped.

In `constructors.jl`, line 62 should be `symname, gendecl(decl)`. I will push a new commit.

Thanks for the updates with the `-`, I would have never thought of this!

As for the reordering of the `include`, thank you as well, was this causing you some issues?

**Comment by jverzani** [comment]
> My bad, this is a mistake in the code I shipped.

No "bad" -- this is all good and very much appreciated!
> 
> As for the reordering of the `include`, thank you as well, was this causing you some issues?

Yes, there was an error on loading (I'd guess you are using Revise to develop which can mask these little things).

Once the CI passes, is this ready to go? The doctests seem to pass.

**Comment by matthieubulte** [comment]
> Yes, there was an error on loading (I'd guess you are using Revise to develop which can mask these little things).

Ah, well, the readme of Revise mention that vscode implements a similar mechanism, so... yes.

> Once the CI passes, is this ready to go? The doctests seem to pass.

There is still your PR open in my fork. What would you prefer:
merge your pr -> merge this pr
or 
merge this pr -> you merge your pr to the official repo

?

**Comment by jverzani** [comment]
Why don't you merge my docs changes into your PR, then I can merge it all together. That should be the most straightforward. (It could be either, whatever is less trouble for you.)

**Comment by jverzani** [comment]
Awesome. Thanks so much for this!! When I get time tomorrow, I'll run the doctests to update those, and tag a new release.

**Pull request merged**
